<?php
/**
* Plugin Name: Remove items from the admin bar
* Plugin URI: https://github.com/TaylorJadin/tiny-wordpress-plugins
* Description: This plugin removes things from the admin bar in wordpress. Thanks to: https://jasonyingling.me/removing-items-from-the-wordpress-admin-bar/
* Version: 1.0
* Author: Taylor Jadin
* Author URI: https://jadin.me/
**/

/* remove stuff from admin bar */
function remove_from_admin_bar($wp_admin_bar) {
    /*
     * Placing items in here will only remove them from admin bar
     * when viewing the fronte end of the site
    */
    if ( ! is_admin() ) {
        // Remove item generated by plugin. Full ID is #wp-admin-bar-si_menu
        //$wp_admin_bar->remove_node('si_menu');
 
        // WordPress Core Items (uncomment to remove)
        //$wp_admin_bar->remove_node('updates');
        $wp_admin_bar->remove_node('comments');
        $wp_admin_bar->remove_node('new-content');
        $wp_admin_bar->remove_node('wp-logo');
        //$wp_admin_bar->remove_node('site-name');
        //$wp_admin_bar->remove_node('my-account');
        $wp_admin_bar->remove_node('search');
        $wp_admin_bar->remove_node('customize');
    }
 
    /*
     * Items placed outside the if statement will remove it from both the frontend
     * and backend of the site
    */
    //$wp_admin_bar->remove_node('wp-logo');
}
add_action('admin_bar_menu', 'remove_from_admin_bar', 999);
?>